### PR TITLE
wxGTK is only for linux

### PR DESCRIPTION
**Pull request by robbycandra**
wxGTK is only for linux.

I hope i send PR to right branch .

### CODE REVIEW

**Comment by robbycandra** [comment]
I still cannot link on windows.....

```
D:\MyApps\Slicer\Slic3r\build>MINGW32-MAKE
[  2%] Built target clipper
[ 60%] Built target libslic3r
[ 62%] Built target ZipArchive
[ 64%] Built target BSpline
[ 68%] Built target expat
[ 76%] Built target admesh
[ 78%] Built target polypartition
[ 84%] Built target poly2tri
[ 95%] Built target slic3r_gui
[ 97%] Built target boost-nowide
[ 98%] Linking CXX executable slic3r.exe
CMakeFiles\slic3r.dir/objects.a(slic3r.cpp.obj): In function `ZNK12wxWindowBase19DoGetBestClientSizeEv':
C:/wxWidgets-3.1.1/include/wx/window.h:1817: undefined reference to `wxDefaultSize'
C:/wxWidgets-3.1.1/include/wx/window.h:1817: undefined reference to `wxDefaultSize'
CMakeFiles\slic3r.dir/objects.a(slic3r.cpp.obj): In function `ZN8wxWindow20MSWEndDeferWindowPosEv':
C:/wxWidgets-3.1.1/include/wx/msw/window.h:737: undefined reference to `wxDefaultPosition'
C:/wxWidgets-3.1.1/include/wx/msw/window.h:737: undefined reference to `wxDefaultPosition'
C:/wxWidgets-3.1.1/include/wx/msw/window.h:738: undefined reference to `wxDefaultSize'
C:/wxWidgets-3.1.1/include/wx/msw/window.h:738: undefined reference to `wxDefaultSize'
.
.
.
liblibslic3r.a(BridgeDetector.cpp.obj): In function `_static_initialization_and_destruction_0':
C:/dev/boost_1_63_0/boost/system/error_code.hpp:221: undefined reference to `boost::system::generic_category()'
C:/dev/boost_1_63_0/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
C:/dev/boost_1_63_0/boost/system/error_code.hpp:223: undefined reference to `boost::system::system_category()'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\slic3r.dir\build.make:101: recipe for target 'slic3r.exe' failed
MINGW32-MAKE[2]: *** [slic3r.exe] Error 1
CMakeFiles\Makefile2:371: recipe for target 'CMakeFiles/slic3r.dir/all' failed
MINGW32-MAKE[1]: *** [CMakeFiles/slic3r.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
MINGW32-MAKE: *** [all] Error 2

```

**Comment by TheThirdOne** [comment]
You are building off of cpp-gui rather than master. I am not sure what the exact status of cpp-gui is, but it is not intended to be stable yet so it is not surprising there are some issues on Windows.

My commits have been on master and the build instructions on the Slic3r wiki should be sufficient to get it working. If you haven't built Slic3r before, I would recommend doing it with the main repos's master first. In general, I don't expect to have broken anything, but the main repo is nearly guaranteed to be non-broken.

**Comment by robbycandra** [comment]
Yes... i have successfully build the master branch. But i am not interested in PERL gui.

**Comment by TheThirdOne** [comment]
Well, I have only been working on the Perl gui thus far. So If your not interested in it, you probably shouldn't be looking at this fork.

**Comment by robbycandra** [comment]
Hahaha.... OK.... but the slicer.cpp is very tempting.

**Pull request closed without merging**
